### PR TITLE
fix(release): fix release failing tests

### LINKED ISSUE #15: Release is throwing errors
https://github.com/adamdotai/date-io/runs/4368459679?check_suite_focus=true

### PR DESCRIPTION
**Pull request by zakariahassan10**
closes #15

### CODE REVIEW

File: packages/hijri/src/index.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import Moment from "moment";
 import iMoment from "moment-hijri";
-import DefaultMomentUtils from "@adamdotai/date-moment";
+import DefaultMomentUtils from "@date-io/moment";
```
Comment (menna-mostafa) [inline packages/hijri/src/index.ts]: @zakariahassan10 is it intentional?

Comment (zakariahassan10) [reply packages/hijri/src/index.ts]: no it wasn't intentional, i reverted it
